{% set name = "geograpy3" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geograpy3-{{ version }}.tar.gz
  sha256: 89552642f6c639d66cbc716abe0a4e047974aa2a2d4b09ad121a438738d3ba7c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >={{ python_min }}
    - setuptools
  run:
    - jellyfish
    - newspaper3k
    - nltk
    - numpy
    - pandas
    - pylodstorage
    - python >={{ python_min }}
    - scikit-learn
    - sphinx_rtd_theme

test:
  imports:
    - geograpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/somnathrakshit/geograpy3
  summary: Extract countries, regions and cities from a URL or text
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
