{% set name = "geograpy3" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geograpy3-{{ version }}.tar.gz
  sha256: 52e7a65a4f39b3fbe84f752814b701bb4093798b22c638622fbcd3445d3a862e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jellyfish
    - newspaper3k
    - nltk
    - numpy
    - pandas
    - pylodstorage
    - python >={{ python_min }}
    - scikit-learn
    - sphinx_rtd_theme

test:
  imports:
    - geograpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/somnathrakshit/geograpy3
  summary: Extract countries, regions and cities from a URL or text
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
